### ISSUE TITLE
minesweeper reset

### ISSUE THREAD

**Issue by bdelanghe** [mappum/0x10code#35]
Reset failed to load new mines.

**Comment by darkhog** [comment]
That's because the only way to make proper seed for random number generator is to somehow count time before user press start game, or count keyboard presses. Think of it as of making new minecraft worlds with same seed over and over again. It simply won't be different any single time unless method of calculation random numbers from seed will change.

**Comment by bdelanghe** [comment]
Thanks that makes perfect sense.
