### ISSUE TITLE
Blinking not implemented

### ISSUE THREAD

**Issue by tjohnman** [mappum/0x10code#39]
The virtual LEM1802 does not make characters blink when their bit 7 is set.

**Comment by darkhog** [comment]
If it's so, that is clearly regression, because it worked when 0x10co.de was 1.1-compliant.

Try such simple code

;for simplicity we will skip hardware mapping
set a, 65 ; "A" letter
add a, 128 ;should make it blink
bor a, 0xF000 ;white on black
set [whatever address you gave your screen ram], a ; plots letter in a register to vram
